name: Shopify Report Automate

on:
  schedule:
    - cron: "30 8 * * *"   # 15:30 WIB = 08:30 UTC
  workflow_dispatch:       # tetap bisa dijalankan manual juga

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
  run: |
    if [ -f requirements.txt ]; then
      pip install -r requirements.txt
    else
      pip install requests pandas openpyxl python-dotenv schedule
    fi

      - name: Run script
        run: python your_script.py
